name: Deploy Frontend to Azure Storage

on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual trigger

env:
  AZURE_STORAGE_ACCOUNT: "sairesumestorage"
  RESOURCE_GROUP: "sai_portfolio"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Upload HTML files"
        run: |
          az storage blob upload-batch \
          --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
          --destination '$web' \
          --source ./frontend \
          --pattern "*.html" \
          --overwrite \
          --auth-mode login

      - name: "Upload CSS files"
        run: |
          az storage blob upload-batch \
          --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
          --destination '$web' \
          --source ./frontend \
          --pattern "*.css" \
          --overwrite \
          --auth-mode login

      - name: Display website URL
        run: |
          echo "Website deployed successfully!"
          echo "URL: https://${{ env.AZURE_STORAGE_ACCOUNT }}.z13.web.core.windows.net"
