name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: "sai-portfolio-function"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./backend/api"
  AZURE_STORAGE_ACCOUNT: "sairesumestorage"
  RESOURCE_GROUP: "sai_portfolio"
  PYTHON_VERSION: "3.9"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: "Resolve Project Dependencies"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd

      - name: "Deploy Azure Function"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: "Clear existing website files"
        run: |
          az storage blob delete-batch \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --source '$web' \
            --auth-mode login

      - name: "Upload website to blob storage"
        run: |
          az storage blob upload-batch \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source ./frontend \
            --overwrite \
            --auth-mode login
